// Generated by contracts/generate.mjs. Do not edit.
using System;
using System.Text.Json;
using System.Text.Json.Serialization;
namespace CoreVideoPro.MediaCore.Contracts;
public sealed class ContractIntegerConverter : JsonConverter<int> {
  public override int Read(ref Utf8JsonReader reader, Type type, JsonSerializerOptions options) {
    if (reader.TokenType != JsonTokenType.Number || !reader.TryGetDouble(out var value) || !double.IsFinite(value) || Math.Truncate(value) != value || value < int.MinValue || value > int.MaxValue) throw new JsonException("Expected a 32-bit integer");
    return (int)value;
  }
  public override void Write(Utf8JsonWriter writer, int value, JsonSerializerOptions options) => writer.WriteNumberValue(value);
}
public sealed record ProtocolVersion {
  [JsonConverter(typeof(ContractIntegerConverter))]
  [JsonPropertyName("major")] public required int Major { get; init; }
  [JsonConverter(typeof(ContractIntegerConverter))]
  [JsonPropertyName("minor")] public required int Minor { get; init; }
}
public static class ProtocolVersionContract {
  public static bool Validate(JsonElement value) {
    if (value.ValueKind != JsonValueKind.Object) return false;
    var hasMajor = value.TryGetProperty("major", out var major);
    if (!hasMajor || !(major.ValueKind == JsonValueKind.Number && major.TryGetDouble(out var majorNumber) && double.IsFinite(majorNumber) && Math.Truncate(majorNumber) == majorNumber && majorNumber >= 1 && majorNumber <= 1)) return false;
    var hasMinor = value.TryGetProperty("minor", out var minor);
    if (!hasMinor || !(minor.ValueKind == JsonValueKind.Number && minor.TryGetDouble(out var minorNumber) && double.IsFinite(minorNumber) && Math.Truncate(minorNumber) == minorNumber && minorNumber >= 0 && minorNumber <= 2147483647)) return false;
    return true;
  }
}
public sealed record OutputLifecycle {
  [JsonPropertyName("sessionId")] public required string SessionId { get; init; }
  [JsonPropertyName("desiredActive")] public required bool DesiredActive { get; init; }
  [JsonPropertyName("state")] public required string State { get; init; }
  [JsonPropertyName("health")] public required string Health { get; init; }
  [JsonPropertyName("finalized")] public required bool Finalized { get; init; }
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("error")] public string? Error { get; init; }
}
public static class OutputLifecycleContract {
  public static bool Validate(JsonElement value) {
    if (value.ValueKind != JsonValueKind.Object) return false;
    var hasSessionId = value.TryGetProperty("sessionId", out var sessionId);
    if (!hasSessionId || !(sessionId.ValueKind == JsonValueKind.String && sessionId.GetString()!.Length >= 1)) return false;
    var hasDesiredActive = value.TryGetProperty("desiredActive", out var desiredActive);
    if (!hasDesiredActive || !((desiredActive.ValueKind == JsonValueKind.True || desiredActive.ValueKind == JsonValueKind.False))) return false;
    var hasState = value.TryGetProperty("state", out var state);
    if (!hasState || !(state.ValueKind == JsonValueKind.String && (state.GetString() == "idle" || state.GetString() == "starting" || state.GetString() == "live" || state.GetString() == "stopping" || state.GetString() == "finalizing" || state.GetString() == "completed" || state.GetString() == "failed" || state.GetString() == "interrupted"))) return false;
    var hasHealth = value.TryGetProperty("health", out var health);
    if (!hasHealth || !(health.ValueKind == JsonValueKind.String && (health.GetString() == "unknown" || health.GetString() == "healthy" || health.GetString() == "degraded" || health.GetString() == "failed"))) return false;
    var hasFinalized = value.TryGetProperty("finalized", out var finalized);
    if (!hasFinalized || !((finalized.ValueKind == JsonValueKind.True || finalized.ValueKind == JsonValueKind.False))) return false;
    var hasError = value.TryGetProperty("error", out var error);
    if (hasError && !(error.ValueKind == JsonValueKind.String)) return false;
    return true;
  }
}
public sealed record OperationStatus {
  [JsonPropertyName("processEpoch")] public required string ProcessEpoch { get; init; }
  [JsonPropertyName("operationId")] public required string OperationId { get; init; }
  [JsonPropertyName("state")] public required string State { get; init; }
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("error")] public string? Error { get; init; }
}
public static class OperationStatusContract {
  public static bool Validate(JsonElement value) {
    if (value.ValueKind != JsonValueKind.Object) return false;
    var hasProcessEpoch = value.TryGetProperty("processEpoch", out var processEpoch);
    if (!hasProcessEpoch || !(processEpoch.ValueKind == JsonValueKind.String && processEpoch.GetString()!.Length >= 1)) return false;
    var hasOperationId = value.TryGetProperty("operationId", out var operationId);
    if (!hasOperationId || !(operationId.ValueKind == JsonValueKind.String && operationId.GetString()!.Length >= 1)) return false;
    var hasState = value.TryGetProperty("state", out var state);
    if (!hasState || !(state.ValueKind == JsonValueKind.String && (state.GetString() == "accepted" || state.GetString() == "running" || state.GetString() == "completed" || state.GetString() == "failed" || state.GetString() == "cancelled"))) return false;
    var hasError = value.TryGetProperty("error", out var error);
    if (hasError && !(error.ValueKind == JsonValueKind.String)) return false;
    return true;
  }
}
public sealed record ProtocolFailure {
  [JsonPropertyName("code")] public required string Code { get; init; }
  [JsonPropertyName("message")] public required string Message { get; init; }
}
public static class ProtocolFailureContract {
  public static bool Validate(JsonElement value) {
    if (value.ValueKind != JsonValueKind.Object) return false;
    var hasCode = value.TryGetProperty("code", out var code);
    if (!hasCode || !(code.ValueKind == JsonValueKind.String && code.GetString()!.Length >= 1)) return false;
    var hasMessage = value.TryGetProperty("message", out var message);
    if (!hasMessage || !(message.ValueKind == JsonValueKind.String && message.GetString()!.Length >= 1)) return false;
    return true;
  }
}
