// Generated by contracts/generate.mjs. Do not edit.
import Foundation
import CoreFoundation
struct ProtocolVersion: Codable {
  var major: Int
  var minor: Int
}
func validateProtocolVersion(_ value: [String: Any]) -> Bool {
  if let raw = value["major"] {
    guard let parsed = raw as? NSNumber else { return false }
    if CFGetTypeID(parsed) == CFBooleanGetTypeID() { return false }
    if parsed.doubleValue.rounded() != parsed.doubleValue || parsed.doubleValue < 1 || parsed.doubleValue > 1 { return false }
  } else { return false }
  if let raw = value["minor"] {
    guard let parsed = raw as? NSNumber else { return false }
    if CFGetTypeID(parsed) == CFBooleanGetTypeID() { return false }
    if parsed.doubleValue.rounded() != parsed.doubleValue || parsed.doubleValue < 0 || parsed.doubleValue > 2147483647 { return false }
  } else { return false }
  return true;
}
struct OutputLifecycle: Codable {
  var sessionId: String
  var desiredActive: Bool
  var state: String
  var health: String
  var finalized: Bool
  var error: String? = nil
}
func validateOutputLifecycle(_ value: [String: Any]) -> Bool {
  if let raw = value["sessionId"] {
    guard let parsed = raw as? String else { return false }
    if parsed.isEmpty { return false }
  } else { return false }
  if let raw = value["desiredActive"] {
    guard let parsed = raw as? NSNumber else { return false }
    if CFGetTypeID(parsed) != CFBooleanGetTypeID() { return false }
  } else { return false }
  if let raw = value["state"] {
    guard let parsed = raw as? String else { return false }
    if !["idle","starting","live","stopping","finalizing","completed","failed","interrupted"].contains(parsed) { return false }
  } else { return false }
  if let raw = value["health"] {
    guard let parsed = raw as? String else { return false }
    if !["unknown","healthy","degraded","failed"].contains(parsed) { return false }
  } else { return false }
  if let raw = value["finalized"] {
    guard let parsed = raw as? NSNumber else { return false }
    if CFGetTypeID(parsed) != CFBooleanGetTypeID() { return false }
  } else { return false }
  if let raw = value["error"] {
    guard let parsed = raw as? String else { return false }
    _ = parsed
  }
  return true;
}
struct OperationStatus: Codable {
  var processEpoch: String
  var operationId: String
  var state: String
  var error: String? = nil
}
func validateOperationStatus(_ value: [String: Any]) -> Bool {
  if let raw = value["processEpoch"] {
    guard let parsed = raw as? String else { return false }
    if parsed.isEmpty { return false }
  } else { return false }
  if let raw = value["operationId"] {
    guard let parsed = raw as? String else { return false }
    if parsed.isEmpty { return false }
  } else { return false }
  if let raw = value["state"] {
    guard let parsed = raw as? String else { return false }
    if !["accepted","running","completed","failed","cancelled"].contains(parsed) { return false }
  } else { return false }
  if let raw = value["error"] {
    guard let parsed = raw as? String else { return false }
    _ = parsed
  }
  return true;
}
struct ProtocolFailure: Codable {
  var code: String
  var message: String
}
func validateProtocolFailure(_ value: [String: Any]) -> Bool {
  if let raw = value["code"] {
    guard let parsed = raw as? String else { return false }
    if parsed.isEmpty { return false }
  } else { return false }
  if let raw = value["message"] {
    guard let parsed = raw as? String else { return false }
    if parsed.isEmpty { return false }
  } else { return false }
  return true;
}
