// Generated by contracts/observation.mjs. Do not edit.
using System.Text;
using System.Text.Json;
namespace CoreVideoPro.MediaCore.Services;
/// <summary>The core session state with three declared observation views.</summary>
public sealed class CoreObservationModel
{
    private readonly JsonElement _root;
    private CoreObservationModel(JsonElement root) => _root = root;
    public static CoreObservationModel Parse(string json)
    {
        using var document = JsonDocument.Parse(json);
        if (document.RootElement.ValueKind != JsonValueKind.Object) throw new JsonException("Core observation must be an object.");
        return new CoreObservationModel(document.RootElement.Clone());
    }
    public JsonElement? Get(string name) => _root.TryGetProperty(name, out var value) ? value : null;
    public JsonElement? Active => Get("active");
    public JsonElement? ActiveSpeakerId => Get("activeSpeakerId");
    public JsonElement? AudioMixSession => Get("audioMixSession");
    public JsonElement? AudioRoutingMatrix => Get("audioRoutingMatrix");
    public JsonElement? AutoProduction => Get("autoProduction");
    public JsonElement? BrandKit => Get("brandKit");
    public JsonElement? BreakoutRoomId => Get("breakoutRoomId");
    public JsonElement? BreakoutRoomName => Get("breakoutRoomName");
    public JsonElement? BrowserSources => Get("browserSources");
    public JsonElement? CaptionTrack => Get("captionTrack");
    public JsonElement? CaptureAudioSources => Get("captureAudioSources");
    public JsonElement? CaptureDevices => Get("captureDevices");
    public JsonElement? Codec => Get("codec");
    public JsonElement? CommandProtocolFailures => Get("commandProtocolFailures");
    public JsonElement? Compositor => Get("compositor");
    public JsonElement? CompositorRenderer => Get("compositorRenderer");
    public JsonElement? Encoder => Get("encoder");
    public JsonElement? EncoderEvidence => Get("encoderEvidence");
    public JsonElement? EncoderSession => Get("encoderSession");
    public JsonElement? HardwareEncoder => Get("hardwareEncoder");
    public JsonElement? Health => Get("health");
    public JsonElement? IsoParticipantIds => Get("isoParticipantIds");
    public JsonElement? IsoSourceIds => Get("isoSourceIds");
    public JsonElement? MediaPlayback => Get("mediaPlayback");
    public JsonElement? MediaSources => Get("mediaSources");
    public JsonElement? MeetingState => Get("meetingState");
    public JsonElement? MultiviewSharedTexture => Get("multiviewSharedTexture");
    public JsonElement? Multiviewer => Get("multiviewer");
    public JsonElement? NativeDiagnostics => Get("nativeDiagnostics");
    public JsonElement? OutputProfile => Get("outputProfile");
    public JsonElement? OutputSenderSession => Get("outputSenderSession");
    public JsonElement? Outputs => Get("outputs");
    public JsonElement? OverlayCount => Get("overlayCount");
    public JsonElement? OverlayState => Get("overlayState");
    public JsonElement? Participants => Get("participants");
    public JsonElement? PreviewScene => Get("previewScene");
    public JsonElement? PreviewSharedTexture => Get("previewSharedTexture");
    public JsonElement? Profile => Get("profile");
    public JsonElement? ProgramBuffer => Get("programBuffer");
    public JsonElement? ProgramFrame => Get("programFrame");
    public JsonElement? ProgramFrameCount => Get("programFrameCount");
    public JsonElement? ProgramFramePreview => Get("programFramePreview");
    public JsonElement? ProgramSharedTexture => Get("programSharedTexture");
    public JsonElement? RealtimeEvidence => Get("realtimeEvidence");
    public JsonElement? Recording => Get("recording");
    public JsonElement? RenderPlanId => Get("renderPlanId");
    public JsonElement? RouteCount => Get("routeCount");
    public JsonElement? RosterEpoch => Get("rosterEpoch");
    public JsonElement? RosterRevision => Get("rosterRevision");
    public JsonElement? SceneId => Get("sceneId");
    public JsonElement? Sources => Get("sources");
    public JsonElement? TakeRecords => Get("takeRecords");
    public JsonElement? TakeTransition => Get("takeTransition");
    public JsonElement? Tiles => Get("tiles");
    public JsonElement? TransformCount => Get("transformCount");
    public JsonElement? VirtualCamera => Get("virtualCamera");
    public JsonElement? Zoom => Get("zoom");
    public JsonElement? ZoomSubscriptionChurn => Get("zoomSubscriptionChurn");
    public string TypedJson() => Project(View.Typed);
    public string QualificationJson() => Project(View.Qualification);
    public string ControlJson() => Project(View.Control);
    private enum View { Typed, Qualification, Control }
    private string Project(View view)
    {
        using var stream = new MemoryStream();
        using (var writer = new Utf8JsonWriter(stream))
        {
            writer.WriteStartObject();
            foreach (var property in _root.EnumerateObject())
            {
                // Unknown fields remain available for older/synthetic wire shapes. The
                // generator checks every field emitted by the native core at build time.
                var policy = Policy(property.Name, view);
                if (policy == 0) continue;
                writer.WritePropertyName(property.Name);
                if (policy == 2) writer.WriteStringValue("[redacted]");
                else property.Value.WriteTo(writer);
            }
            writer.WriteEndObject();
        }
        var json = Encoding.UTF8.GetString(stream.ToArray());
        return view == View.Typed ? json : CoreSnapshotObserver.Redact(json);
    }
    // 0 = omit, 1 = include, 2 = redact. Unknown fields are carried through
    // for forward wire compatibility and still recursively redacted at egress.
    private static int Policy(string field, View view) => field switch
    {
        "active" => view switch { View.Typed => 0, View.Qualification => 1, _ => 1 },
        "activeSpeakerId" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "audioMixSession" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "audioRoutingMatrix" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "autoProduction" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "brandKit" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "breakoutRoomId" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "breakoutRoomName" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "browserSources" => view switch { View.Typed => 0, View.Qualification => 1, _ => 1 },
        "captionTrack" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "captureAudioSources" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "captureDevices" => view switch { View.Typed => 0, View.Qualification => 1, _ => 1 },
        "codec" => view switch { View.Typed => 0, View.Qualification => 1, _ => 1 },
        "commandProtocolFailures" => view switch { View.Typed => 0, View.Qualification => 1, _ => 1 },
        "compositor" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "compositorRenderer" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "encoder" => view switch { View.Typed => 0, View.Qualification => 1, _ => 1 },
        "encoderEvidence" => view switch { View.Typed => 0, View.Qualification => 1, _ => 1 },
        "encoderSession" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "hardwareEncoder" => view switch { View.Typed => 0, View.Qualification => 1, _ => 1 },
        "health" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "isoParticipantIds" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "isoSourceIds" => view switch { View.Typed => 0, View.Qualification => 1, _ => 1 },
        "mediaPlayback" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "mediaSources" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "meetingState" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "multiviewSharedTexture" => view switch { View.Typed => 0, View.Qualification => 1, _ => 1 },
        "multiviewer" => view switch { View.Typed => 0, View.Qualification => 1, _ => 1 },
        "nativeDiagnostics" => view switch { View.Typed => 0, View.Qualification => 1, _ => 1 },
        "outputProfile" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "outputSenderSession" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "outputs" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "overlayCount" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "overlayState" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "participants" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "previewScene" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "previewSharedTexture" => view switch { View.Typed => 0, View.Qualification => 1, _ => 1 },
        "profile" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "programBuffer" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "programFrame" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "programFrameCount" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "programFramePreview" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "programSharedTexture" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "realtimeEvidence" => view switch { View.Typed => 0, View.Qualification => 1, _ => 1 },
        "recording" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "renderPlanId" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "routeCount" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "rosterEpoch" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "rosterRevision" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "sceneId" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "sources" => view switch { View.Typed => 0, View.Qualification => 1, _ => 1 },
        "takeRecords" => view switch { View.Typed => 0, View.Qualification => 1, _ => 1 },
        "takeTransition" => view switch { View.Typed => 0, View.Qualification => 1, _ => 1 },
        "tiles" => view switch { View.Typed => 0, View.Qualification => 1, _ => 1 },
        "transformCount" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "virtualCamera" => view switch { View.Typed => 1, View.Qualification => 1, _ => 1 },
        "zoom" => view switch { View.Typed => 0, View.Qualification => 1, _ => 1 },
        "zoomSubscriptionChurn" => view switch { View.Typed => 0, View.Qualification => 1, _ => 1 },
        _ => 1
    };
}
