// Intentionally small schema compiler: the supported subset is checked explicitly.
// It generates runtime validation as well as DTOs; adding unsupported schema keywords
// fails generation instead of silently weakening the wire contract.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const schema = JSON.parse(readFileSync(resolve(root, 'contracts/lifecycle.schema.json'), 'utf8'));
const check = process.argv.includes('--check');
const q = JSON.stringify;
const pascal = s => s[0].toUpperCase() + s.slice(1);
const definitions = Object.entries(schema.$defs);
for (const [name, definition] of definitions) {
  if (definition.type !== 'object' || definition.additionalProperties !== true) throw Error(`Unsupported object ${name}`);
  for (const key of Object.keys(definition)) if (!['type', 'additionalProperties', 'required', 'properties'].includes(key)) throw Error(`Unsupported object keyword ${name}.${key}`);
  if (!Array.isArray(definition.required) || new Set(definition.required).size !== definition.required.length || definition.required.some(field => !(field in definition.properties))) throw Error(`Invalid required fields in ${name}`);
  for (const [field, rule] of Object.entries(definition.properties)) {
    if (!['string', 'integer', 'boolean'].includes(rule.type)) throw Error(`Unsupported type ${name}.${field}`);
    for (const key of Object.keys(rule)) if (!['type', 'enum', 'minLength', 'minimum', 'maximum'].includes(key)) throw Error(`Unsupported keyword ${key}`);
    if (rule.enum && (rule.type !== 'string' || !Array.isArray(rule.enum) || rule.enum.length === 0 || rule.enum.some(value => typeof value !== 'string'))) throw Error(`Unsupported enum ${name}.${field}`);
    // Longer JSON Schema string lengths count Unicode code points, whereas the
    // native standard libraries count bytes/code units/graphemes differently.
    // Support nonempty only until a shared Unicode-length implementation exists.
    if ('minLength' in rule && (rule.type !== 'string' || rule.minLength !== 1)) throw Error(`Unsupported string length ${name}.${field}`);
    if (rule.type === 'integer' && (!Number.isInteger(rule.minimum) || !Number.isInteger(rule.maximum) || rule.minimum < -2147483648 || rule.maximum > 2147483647 || rule.minimum > rule.maximum)) throw Error(`Integer bounds must fit Int32: ${name}.${field}`);
    if (rule.type !== 'integer' && ('minimum' in rule || 'maximum' in rule)) throw Error(`Invalid numeric bounds ${name}.${field}`);
  }
}

const ts = ['// Generated by contracts/generate.mjs. Do not edit.'];
const cpp = ['// Generated by contracts/generate.mjs. Do not edit.', '#pragma once', '#include "rpc/Json.h"', '#include <cmath>', '#include <optional>', '#include <string>', 'namespace corevideo::contracts {'];
const cs = ['// Generated by contracts/generate.mjs. Do not edit.', 'using System;', 'using System.Text.Json;', 'using System.Text.Json.Serialization;', 'namespace CoreVideoPro.MediaCore.Contracts;',
  'public sealed class ContractIntegerConverter : JsonConverter<int> {',
  '  public override int Read(ref Utf8JsonReader reader, Type type, JsonSerializerOptions options) {',
  '    if (reader.TokenType != JsonTokenType.Number || !reader.TryGetDouble(out var value) || !double.IsFinite(value) || Math.Truncate(value) != value || value < int.MinValue || value > int.MaxValue) throw new JsonException("Expected a 32-bit integer");',
  '    return (int)value;', '  }',
  '  public override void Write(Utf8JsonWriter writer, int value, JsonSerializerOptions options) => writer.WriteNumberValue(value);', '}'];
const swift = ['// Generated by contracts/generate.mjs. Do not edit.', 'import Foundation'];

for (const [name, def] of definitions) {
  const fields = Object.entries(def.properties);
  const required = field => def.required.includes(field);
  ts.push(`export type ${name} = {`);
  cpp.push(`struct ${name} {`);
  cs.push(`public sealed record ${name} {`);
  swift.push(`struct ${name}: Codable {`);
  for (const [field, rule] of fields) {
    const tsType = rule.enum ? rule.enum.map(q).join(' | ') : {string:'string',integer:'number',boolean:'boolean'}[rule.type];
    const cppType = {string:'std::string',integer:'int',boolean:'bool'}[rule.type];
    const csType = {string:'string',integer:'int',boolean:'bool'}[rule.type];
    const swiftType = {string:'String',integer:'Int',boolean:'Bool'}[rule.type];
    ts.push(`  ${field}${required(field) ? '' : '?'}: ${tsType};`);
    cpp.push(`  ${required(field) ? cppType : `std::optional<${cppType}>`} ${field}{};`);
    if (!required(field)) cs.push('  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]');
    if (rule.type === 'integer') cs.push('  [JsonConverter(typeof(ContractIntegerConverter))]');
    cs.push(`  [JsonPropertyName(${q(field)})] public ${required(field) ? 'required ' : ''}${csType}${required(field) ? '' : '?'} ${pascal(field)} { get; init; }`);
    swift.push(`  var ${field}: ${swiftType}${required(field) ? '' : '?'}${required(field) ? '' : ' = nil'}`);
  }
  ts.push('};'); cpp.push('};'); cs.push('}'); swift.push('}');

  ts.push(`export function validate${name}(value: unknown): value is ${name} {`, '  if (typeof value !== "object" || value === null || Array.isArray(value)) return false;', '  const v = value as Record<string, unknown>;');
  cpp.push(`inline bool validate${name}(const rpc::Json& value) {`, '  if (!value.isObject()) return false;');
  cs.push(`public static class ${name}Contract {`, '  public static bool Validate(JsonElement value) {', '    if (value.ValueKind != JsonValueKind.Object) return false;');
  swift.push(`func validate${name}(_ value: [String: Any]) -> Bool {`);
  for (const [field, rule] of fields) {
    const v = `v[${q(field)}]`;
    const tsConditions = [`typeof ${v} === ${q(rule.type === 'integer' ? 'number' : rule.type)}`];
    if (rule.type === 'integer') tsConditions.push(`Number.isInteger(${v})`, `${v} as number >= ${rule.minimum}`, `${v} as number <= ${rule.maximum}`);
    if (rule.minLength) tsConditions.push(`(${v} as string).length >= ${rule.minLength}`);
    if (rule.enum) tsConditions.push(`${q(rule.enum)}.includes(${v} as string)`);
    ts.push(`  if (${required(field) ? '' : `${v} !== undefined && `}!(${tsConditions.join(' && ')})) return false;`);

    cpp.push(`  const auto* ${field} = value.get(${q(field)});`);
    const cc = [`${field}->${{string:'isString',integer:'isNumber',boolean:'isBool'}[rule.type]}()`];
    if (rule.type === 'integer') cc.push(`std::floor(${field}->asNumber()) == ${field}->asNumber()`, `${field}->asNumber() >= ${rule.minimum}`, `${field}->asNumber() <= ${rule.maximum}`);
    if (rule.minLength) cc.push(`${field}->asString().size() >= ${rule.minLength}`);
    if (rule.enum) cc.push(`(${rule.enum.map(x => `${field}->asString() == ${q(x)}`).join(' || ')})`);
    cpp.push(`  if (${required(field) ? `!${field} || ` : `${field} && `}!(${cc.join(' && ')})) return false;`);

    cs.push(`    var has${pascal(field)} = value.TryGetProperty(${q(field)}, out var ${field});`);
    const csc = [`${field}.ValueKind == JsonValueKind.${{string:'String',integer:'Number',boolean:'True'}[rule.type]}`];
    if (rule.type === 'boolean') csc[0] = `(${field}.ValueKind == JsonValueKind.True || ${field}.ValueKind == JsonValueKind.False)`;
    if (rule.type === 'integer') csc.push(`${field}.TryGetDouble(out var ${field}Number)`, `double.IsFinite(${field}Number)`, `Math.Truncate(${field}Number) == ${field}Number`, `${field}Number >= ${rule.minimum}`, `${field}Number <= ${rule.maximum}`);
    if (rule.minLength) csc.push(`${field}.GetString()!.Length >= ${rule.minLength}`);
    if (rule.enum) csc.push(`(${rule.enum.map(x => `${field}.GetString() == ${q(x)}`).join(' || ')})`);
    cs.push(`    if (${required(field) ? `!has${pascal(field)} || ` : `has${pascal(field)} && `}!(${csc.join(' && ')})) return false;`);

    swift.push(`  if let raw = value[${q(field)}] {`);
    if (rule.type === 'string') {
      swift.push('    guard let parsed = raw as? String else { return false }');
      if (rule.minLength) swift.push(`    if parsed.isEmpty { return false }`);
      if (rule.enum) swift.push(`    if !${q(rule.enum)}.contains(parsed) { return false }`);
      if (!rule.enum && !rule.minLength) swift.push('    _ = parsed');
    } else {
      swift.push('    guard let parsed = raw as? NSNumber else { return false }');
      swift.push(`    if ${rule.type === 'boolean' ? 'CFGetTypeID(parsed) != CFBooleanGetTypeID()' : 'CFGetTypeID(parsed) == CFBooleanGetTypeID()'} { return false }`);
      if (rule.type === 'integer') swift.push(`    if parsed.doubleValue.rounded() != parsed.doubleValue || parsed.doubleValue < ${rule.minimum} || parsed.doubleValue > ${rule.maximum} { return false }`);
    }
    swift.push(`  }${required(field) ? ' else { return false }' : ''}`);
  }
  ts.push('  return true;', '}'); cpp.push('  return true;', '}'); cs.push('    return true;', '  }', '}'); swift.push('  return true;', '}');
  cpp.push(`inline rpc::Json toJson(const ${name}& value) {`, '  rpc::Json::Object result;');
  for (const [field] of fields) cpp.push(`  ${required(field) ? '' : `if (value.${field}) `}result.emplace(${q(field)}, ${required(field) ? '' : '*'}value.${field});`);
  cpp.push('  return result;', '}');
}
cpp.push('} // namespace corevideo::contracts');
swift.splice(2, 0, 'import CoreFoundation');
let stale = false;
for (const [path, lines] of [
  ['src/engine/generated/lifecycle.ts', ts],
  ['native-core/src/generated/lifecycle.ts', ts],
  ['native/src/contracts/Lifecycle.h', cpp],
  ['native-shell/CoreVideoPro.MediaCore/Contracts/Lifecycle.cs', cs],
  ['mac-shell/Sources/CoreVideoProShell/Lifecycle.generated.swift', swift]
]) {
  const target = resolve(root, path);
  const content = lines.join('\n') + '\n';
  if (check) {
    let existing = ''; try { existing = readFileSync(target, 'utf8'); } catch {}
    if (existing.replaceAll('\r\n', '\n') !== content) { console.error(`Stale generated contract: ${path}`); stale = true; }
  } else { mkdirSync(dirname(target), {recursive:true}); writeFileSync(target, content); }
}
if (stale) process.exitCode = 1;
