import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const source = readFileSync(resolve(root, 'native/src/core/MediaCore.cpp'), 'utf8');
const start = source.indexOf('rpc::Json MediaCore::sessionState() const {');
const end = source.indexOf('rpc::Json MediaCore::syncZoomMediaSpine', start);
if (start < 0 || end < 0) throw Error('Cannot locate native sessionState()');
const body = source.slice(start, end);
const objectStart = body.indexOf('rpc::Json::Object state{');
const objectEnd = body.indexOf('\n  };', objectStart);
if (objectStart < 0 || objectEnd < 0) throw Error('Cannot locate sessionState object');
const initial = body.slice(objectStart, objectEnd);
const later = body.slice(objectEnd);
const emitted = new Set([
  ...[...initial.matchAll(/^      \{"([^"]+)",/gm)].map(match => match[1]),
  ...[...later.matchAll(/\bstate\.emplace\("([^"]+)"/g)].map(match => match[1])
]);
const spec = JSON.parse(readFileSync(resolve(root, 'contracts/observation.schema.json'), 'utf8'));
const fields = Object.entries(spec.fields);
const valid = new Set(['include', 'omit', 'redact']);
const modelSource = readFileSync(resolve(root, 'native-shell/CoreVideoPro.MediaCore/Models/NativeMediaCoreProtocol.cs'), 'utf8');
const wireSource = readFileSync(resolve(root, 'native-shell/CoreVideoPro.MediaCore/Models/CoreProtocolModels.cs'), 'utf8');
const classProperties = (text, declaration) => {
  const start = text.indexOf(declaration);
  if (start < 0) throw Error(`Cannot locate ${declaration}`);
  const end = text.indexOf('\n}', start);
  if (end < 0) throw Error(`Cannot find end of ${declaration}`);
  return new Set([...text.slice(start, end).matchAll(/public [^\r\n]+? (\w+) \{ get; init; \}/g)]
    .map(match => match[1].toLowerCase()));
};
const typedProperties = new Set([
  ...classProperties(modelSource, 'public sealed record NativeMediaCoreStateSnapshot'),
  ...classProperties(wireSource, 'public sealed class NativeMediaCoreWireState')
]);
for (const [name, policy] of fields) {
  if (!emitted.has(name)) throw Error(`Observation contract declares a field core does not emit: ${name}`);
  for (const view of ['typed', 'qualification', 'control']) {
    if (!valid.has(policy[view])) throw Error(`Missing observation policy: ${name}.${view}`);
  }
  if (Object.keys(policy).some(key => !['typed', 'qualification', 'control'].includes(key)))
    throw Error(`Unknown observation policy on ${name}`);
  if (policy.typed === 'include' && !typedProperties.has(name.toLowerCase()))
    throw Error(`Typed observation includes ${name}, but neither typed snapshot model binds it`);
}
for (const name of emitted) if (!(name in spec.fields))
  throw Error(`Core observation field ${name} needs typed, qualification and control policies`);

const names = fields.map(([name]) => name);
const q = JSON.stringify;
const pascal = name => name[0].toUpperCase() + name.slice(1);
const lines = [
  '// Generated by contracts/observation.mjs. Do not edit.',
  'using System.Text;',
  'using System.Text.Json;',
  'namespace CoreVideoPro.MediaCore.Services;',
  '/// <summary>The core session state with three declared observation views.</summary>',
  'public sealed class CoreObservationModel',
  '{',
  '    private readonly JsonElement _root;',
  '    private CoreObservationModel(JsonElement root) => _root = root;',
  '    public static CoreObservationModel Parse(string json)',
  '    {',
  '        using var document = JsonDocument.Parse(json);',
  '        if (document.RootElement.ValueKind != JsonValueKind.Object) throw new JsonException("Core observation must be an object.");',
  '        return new CoreObservationModel(document.RootElement.Clone());',
  '    }',
  '    public JsonElement? Get(string name) => _root.TryGetProperty(name, out var value) ? value : null;',
  ...names.map(name => `    public JsonElement? ${pascal(name)} => Get(${q(name)});`),
  '    public string TypedJson() => Project(View.Typed);',
  '    public string QualificationJson() => Project(View.Qualification);',
  '    public string ControlJson() => Project(View.Control);',
  '    private enum View { Typed, Qualification, Control }',
  '    private string Project(View view)',
  '    {',
  '        using var stream = new MemoryStream();',
  '        using (var writer = new Utf8JsonWriter(stream))',
  '        {',
  '            writer.WriteStartObject();',
  '            foreach (var property in _root.EnumerateObject())',
  '            {',
  '                // Unknown fields remain available for older/synthetic wire shapes. The',
  '                // generator checks every field emitted by the native core at build time.',
  '                var policy = Policy(property.Name, view);',
  '                if (policy == 0) continue;',
  '                writer.WritePropertyName(property.Name);',
  '                if (policy == 2) writer.WriteStringValue("[redacted]");',
  '                else property.Value.WriteTo(writer);',
  '            }',
  '            writer.WriteEndObject();',
  '        }',
  '        var json = Encoding.UTF8.GetString(stream.ToArray());',
  '        return view == View.Typed ? json : CoreSnapshotObserver.Redact(json);',
  '    }',
  '    // 0 = omit, 1 = include, 2 = redact. Unknown fields are carried through',
  '    // for forward wire compatibility and still recursively redacted at egress.',
  '    private static int Policy(string field, View view) => field switch',
  '    {'
];
for (const [name, policy] of fields) {
  const number = value => ({omit: 0, include: 1, redact: 2})[value];
  lines.push(`        ${q(name)} => view switch { View.Typed => ${number(policy.typed)}, View.Qualification => ${number(policy.qualification)}, _ => ${number(policy.control)} },`);
}
lines.push('        _ => 1', '    };', '}');
const output = lines.join('\n') + '\n';
const target = resolve(root, 'native-shell/CoreVideoPro.MediaCore/Services/CoreObservationModel.g.cs');
if (process.argv.includes('--check')) {
  let current = ''; try { current = readFileSync(target, 'utf8'); } catch {}
  if (current.replaceAll('\r\n', '\n') !== output) throw Error('Stale generated observation model');
} else writeFileSync(target, output);
