// Generated by contracts/generate.mjs. Do not edit.
#pragma once
#include "rpc/Json.h"
#include <cmath>
#include <optional>
#include <string>
namespace corevideo::contracts {
struct ProtocolVersion {
  int major{};
  int minor{};
};
inline bool validateProtocolVersion(const rpc::Json& value) {
  if (!value.isObject()) return false;
  const auto* major = value.get("major");
  if (!major || !(major->isNumber() && std::floor(major->asNumber()) == major->asNumber() && major->asNumber() >= 1 && major->asNumber() <= 1)) return false;
  const auto* minor = value.get("minor");
  if (!minor || !(minor->isNumber() && std::floor(minor->asNumber()) == minor->asNumber() && minor->asNumber() >= 0 && minor->asNumber() <= 2147483647)) return false;
  return true;
}
inline rpc::Json toJson(const ProtocolVersion& value) {
  rpc::Json::Object result;
  result.emplace("major", value.major);
  result.emplace("minor", value.minor);
  return result;
}
struct OutputLifecycle {
  std::string sessionId{};
  bool desiredActive{};
  std::string state{};
  std::string health{};
  bool finalized{};
  std::optional<std::string> error{};
};
inline bool validateOutputLifecycle(const rpc::Json& value) {
  if (!value.isObject()) return false;
  const auto* sessionId = value.get("sessionId");
  if (!sessionId || !(sessionId->isString() && sessionId->asString().size() >= 1)) return false;
  const auto* desiredActive = value.get("desiredActive");
  if (!desiredActive || !(desiredActive->isBool())) return false;
  const auto* state = value.get("state");
  if (!state || !(state->isString() && (state->asString() == "idle" || state->asString() == "starting" || state->asString() == "live" || state->asString() == "stopping" || state->asString() == "finalizing" || state->asString() == "completed" || state->asString() == "failed" || state->asString() == "interrupted"))) return false;
  const auto* health = value.get("health");
  if (!health || !(health->isString() && (health->asString() == "unknown" || health->asString() == "healthy" || health->asString() == "degraded" || health->asString() == "failed"))) return false;
  const auto* finalized = value.get("finalized");
  if (!finalized || !(finalized->isBool())) return false;
  const auto* error = value.get("error");
  if (error && !(error->isString())) return false;
  return true;
}
inline rpc::Json toJson(const OutputLifecycle& value) {
  rpc::Json::Object result;
  result.emplace("sessionId", value.sessionId);
  result.emplace("desiredActive", value.desiredActive);
  result.emplace("state", value.state);
  result.emplace("health", value.health);
  result.emplace("finalized", value.finalized);
  if (value.error) result.emplace("error", *value.error);
  return result;
}
struct OperationStatus {
  std::string processEpoch{};
  std::string operationId{};
  std::string state{};
  std::optional<std::string> error{};
};
inline bool validateOperationStatus(const rpc::Json& value) {
  if (!value.isObject()) return false;
  const auto* processEpoch = value.get("processEpoch");
  if (!processEpoch || !(processEpoch->isString() && processEpoch->asString().size() >= 1)) return false;
  const auto* operationId = value.get("operationId");
  if (!operationId || !(operationId->isString() && operationId->asString().size() >= 1)) return false;
  const auto* state = value.get("state");
  if (!state || !(state->isString() && (state->asString() == "accepted" || state->asString() == "running" || state->asString() == "completed" || state->asString() == "failed" || state->asString() == "cancelled"))) return false;
  const auto* error = value.get("error");
  if (error && !(error->isString())) return false;
  return true;
}
inline rpc::Json toJson(const OperationStatus& value) {
  rpc::Json::Object result;
  result.emplace("processEpoch", value.processEpoch);
  result.emplace("operationId", value.operationId);
  result.emplace("state", value.state);
  if (value.error) result.emplace("error", *value.error);
  return result;
}
struct ProtocolFailure {
  std::string code{};
  std::string message{};
};
inline bool validateProtocolFailure(const rpc::Json& value) {
  if (!value.isObject()) return false;
  const auto* code = value.get("code");
  if (!code || !(code->isString() && code->asString().size() >= 1)) return false;
  const auto* message = value.get("message");
  if (!message || !(message->isString() && message->asString().size() >= 1)) return false;
  return true;
}
inline rpc::Json toJson(const ProtocolFailure& value) {
  rpc::Json::Object result;
  result.emplace("code", value.code);
  result.emplace("message", value.message);
  return result;
}
} // namespace corevideo::contracts
